### ISSUE TITLE
Error: expected { value: 0 } to roughly deeply equal { value: 1e-17 }

### ISSUE THREAD

**Issue by pgorecki** [Turbo87/chai-roughly#1]
Error raised for:

```
expect({ value: 0 }).to.roughly.deep.equal({ value: 1e-17 });
```

which is wrong since 1e-17 < 1e-6 (default tolerance)

**Comment by Turbo87** [comment]
that indeed looks wrong. did you try to step through it in the debugger?

**Comment by Turbo87** [comment]
@pgorecki actually this is not a bug. the `tolerance` value is a percentage value and will be multiplied with the first value to calculate the actual absolute tolerance. since `1e-6 * 0 = 0` there is no tolerance in this case.

**Comment by noru** [comment]
That would be a dead end for comparison with 0 and tiny numbers. It would be better to be able to switch between percentage & absolute value
