### ISSUE TITLE
Roughly assertions with non-deep equal

### ISSUE THREAD

**Issue by ghost** [Turbo87/chai-roughly#2]
Great plugin! It would be excellent if it also worked with regular equals assertions.

`expect(3.99999).to.roughly.equal(4)` --> true

**Comment by Turbo87** [comment]
you can use `expect(3.9999).to.be.closeTo(4, 0.001)` for that (see http://chaijs.com/api/bdd/#method_closeto)

**Comment by ghost** [comment]
No way! Thanks :)

On Tue, May 31, 2016 at 11:09 AM, Tobias Bieniek notifications@github.com
wrote:

> Closed #2 https://github.com/Turbo87/chai-roughly/issues/2.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Turbo87/chai-roughly/issues/2#event-677390642, or mute
> the thread
> https://github.com/notifications/unsubscribe/AOadCX7uAMoIgxVv2PunKxTKzUSPIqKgks5qHHlSgaJpZM4IqyQo
> .

## 

Taylor Denouden
taylor.denouden@hakai.org
