### ISSUE TITLE
TypeScript declarations

### ISSUE THREAD

**Issue by danvk** [Turbo87/chai-roughly#5]
Nice work on this! It's a feature I've always thought was missing from Chai.

In case there are other TypeScript users out there, you can get this to type-check in TS by putting this in a `chai-roughly.d.ts` file somewhere:

``` ts
declare module '~chai/lib/Assertion' {
  export interface Assertion {
    roughly: RoughAssertion;
  }

  interface RoughAssertion extends Assertion {
    (tolerance: number): Assertion;
  }
}
```

**Comment by Turbo87** [comment]
@danvk cool, thanks!
